# Enable reloading this file with <prefix> + r
unbind r
bind r source-file ~/.tmux.conf

set -g mouse on

# True colors
set-option -sa terminal-overrides ",xterm*:Tc"

# Override default prefix
set -g prefix C-s

# Vi mode for copy mode
set-window-option -g mode-keys vi

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name' # requires yq to work
set -g @plugin 'sainnhe/tmux-fzf'

# Session switcher config
set -g @plugin 'brokenricefilms/tmux-fzf-session-switch'
set-option -g @fzf-goto-session-only 'true'

# Theme config
set -g @plugin 'o0th/tmux-nova'
set -g @nova-nerdfonts true

active_bg="#475258"
bg="#343f44"

set -g @nova-segment-session " #{session_name}"
set -g @nova-segment-session-colors "green black"
set -g @nova-segments-0-left "session"
set -gw window-status-current-style bold
set -g status-left-length 100

set -g @nova-pane-justify "left"
set -g @nova-nerdfonts-left 
set -g @nova-nerdfonts-right 
set -g @nova-pane "#I #W"
set -g @nova-rows 0
set -g @nova-pane-active-border-style green
set -g @nova-pane-border-style black
set -g @nova-status-style-bg "$bg"
set -g @nova-status-style-fg white
set -g @nova-status-style-active-bg "$active_bg"
set -g @nova-status-style-active-fg white
set -g @nova-status-style-double-bg default
set -g @nova-segment-prefix "#{?client_prefix, ,}"
set -g @nova-segment-prefix-colors "yellow black"

set -g @nova-segment-custom "%H:%M"
set -g @nova-segment-custom-colors "green black"
set -g @nova-segments-0-right "prefix custom"

# Customize the status line
set -g status-position top
set -g status-interval 1

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
